export { Home } from "./Home"
export { Categories } from "./Categories"
export { Login } from "./Login"
export { Signup } from "./Signup"
export { Rules } from "./Rules"
export { Questions } from "./Questions"
export { Result } from "./Result"
export { NotFound } from "./NotFound"
